# Generated by Django 4.1 on 2023-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_artikl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_machine_sample_number', models.CharField(max_length=200, null=True)),
                ('turbo_maker_oe_no', models.CharField(max_length=200, null=True)),
                ('turbo_maker', models.CharField(max_length=200, null=True)),
                ('turbo_model', models.CharField(max_length=200, null=True)),
                ('vehicle_oem_number', models.CharField(max_length=200, null=True)),
                ('vehicle_brand', models.CharField(max_length=200, null=True)),
                ('vehicle_model', models.CharField(max_length=200, null=True)),
                ('engine', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('complete_turbo_code', models.CharField(max_length=200, null=True)),
                ('gasket_kits', models.CharField(max_length=200, null=True)),
                ('chra', models.CharField(max_length=200, null=True)),
                ('sw', models.CharField(max_length=200, null=True)),
                ('cw', models.CharField(max_length=200, null=True)),
                ('back_plate', models.CharField(max_length=200, null=True)),
                ('thrust_flinger', models.CharField(max_length=200, null=True)),
                ('thrust_bearing', models.CharField(max_length=200, null=True)),
                ('journal_bearing', models.CharField(max_length=200, null=True)),
                ('bearing_housing', models.CharField(max_length=200, null=True)),
                ('actuator', models.CharField(max_length=200, null=True)),
                ('turbine_housing', models.CharField(max_length=200, null=True)),
                ('compressor_housing', models.CharField(max_length=200, null=True)),
                ('nozzle_ring_assembly', models.CharField(max_length=200, null=True)),
                ('repair_kits', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
