# Generated by Django 4.1 on 2023-11-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artikl',
        ),
    ]
