# Generated by Django 4.1 on 2023-11-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delroba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DelRoba',
        ),
    ]
